
INSERT INTO users (name, age) VALUES ("Adam", 3);
INSERT INTO users (name, age) VALUES ("Josh", 43);
INSERT INTO users (name, age) VALUES ("Carl", 22);
INSERT INTO users (name, age) VALUES ("Angie", 21);
INSERT INTO users (name, age) VALUES ("Angel", 10);
INSERT INTO users (name, age) VALUES ("Batman", 19);
INSERT INTO users (name, age) VALUES ("Flash", 12);
INSERT INTO users (name, age) VALUES ("Omar", 15);
INSERT INTO users (name, age) VALUES ("Charlie", 32);
INSERT INTO users (name, age) VALUES ("Charles", 18);
INSERT INTO users (name, age) VALUES ("Chris", 98);
INSERT INTO users (name, age) VALUES ("Cris", 4);
INSERT INTO users (name, age) VALUES ("Paula", 100);
INSERT INTO users (name, age) VALUES ("Fang", 43);
INSERT INTO users (name, age) VALUES ("Ashley", 55);
INSERT INTO users (name, age) VALUES ("Ladey", 92);
INSERT INTO users (name, age) VALUES ("Zeus", 29);
INSERT INTO users (name, age) VALUES ("Maggie", 32);
INSERT INTO users (name, age) VALUES ("Mark", 21);
INSERT INTO users (name, age) VALUES ("Miguel", 5);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project A", "Tech", 50000, "01/01/2019", "01/31/2019");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project B", "Food", 6000, "01/01/2019", "01/31/2019");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project C", "School", 2000, "01/01/2019", "01/31/2019");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project D", "Business", 3000, "01/01/2019", "01/31/2019");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project E", "Food", 89000, "01/01/2019", "01/31/2019");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project F", "Resturant", 8000, "01/01/2019", "01/31/2019");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project G", "Music", 1000, "01/01/2019", "01/31/2019");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project H", "Tech", 3000, "01/01/2019", "01/31/2019");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project I", "Construction", 53000, "01/01/2019", "01/31/2019");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project J", "Tech", 502000, "01/01/2019", "01/31/2019");
INSERT INTO pledges (amount, user_id, project_id) VALUES (random(), 14, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (random(), 19, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (random(), 13, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (random(), 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (random(), 18, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (random(), 8, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (random(), 7, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (random(), 14, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (random(), 13, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (random(), 5, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (random(), 17, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (random(), 11, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (random(), 4, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (random(), 14, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (random(), 8, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (random(), 10, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (random(), 11, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (random(), 8, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (random(), 7, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (random(), 9, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (random(), 8, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (random(), 5, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (random(), 3, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (random(), 20, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (random(), 20, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (random(), 20, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (random(), 18, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (random(), 7, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (random(), 6, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (random(), 4, 3);
